In [1]:
from cashe import get_input
from src.data_local import MergedDataPreprocessing
from src.lstm_encoder import LSTMEmbedding
import time
from src.model_train import encode_label
import numpy as np

#train_columns = ['item_NameEn','item_ResponseState']

In [2]:
df_original = get_input()
preprocessing = MergedDataPreprocessing(df_original)

df_original = preprocessing.age_gender_item_ids_prep(item_encoding=False)
df_train, df_test = preprocessing.train_test_split()

In [3]:
df_train

item_CreatedDate                 transaction_RequestId  \
4     2023-08-24 15:03:23.404  c4427a02-3291-422d-b2e8-b97bf3d5081d   
5     2023-08-29 11:48:54.060  e6f4ad37-13b9-4694-a61b-495384fcd245   
6     2023-08-29 11:48:54.060  e6f4ad37-13b9-4694-a61b-495384fcd245   
18    2023-08-29 12:35:53.514  bba44f35-42ea-4b22-aceb-8d8efaf45f9e   
19    2023-08-29 12:35:53.514  bba44f35-42ea-4b22-aceb-8d8efaf45f9e   
...                       ...                                   ...   
45617 2024-04-23 14:29:40.340  d62d5929-d94d-4a53-830d-168671bbea82   
45618 2024-04-23 16:20:30.584  da54b137-2aca-413a-9388-d9582ee72b57   
45619 2024-04-23 16:20:30.585  da54b137-2aca-413a-9388-d9582ee72b57   
45620 2024-04-23 16:20:30.585  da54b137-2aca-413a-9388-d9582ee72b57   
45621 2024-04-23 16:20:30.585  da54b137-2aca-413a-9388-d9582ee72b57   

       transaction_PatientAge  transaction_PatientEnGender  \
4                           6                            1   
5                          28                            0   
6                          28                            0   
18                         56                            0   
19                         56                            0   
...                       ...                          ...   
45617                      29                            1   
45618                       0                            1   
45619                       0                            1   
45620                       0                            1   
45621                       0                            1   

                               item_NameEn  item_Price  item_Status  \
4                              Examination       80.00            2   
5                              Examination       80.00            6   
6                   PREGNANCY TEST (BLOOD)      175.45            6   
18                             Examination       80.00            2   
19                               PERFALGAN      110.00            2   
...                                    ...         ...          ...   
45617            REPARIL  20 MG 40 DRAGEES       17.92            2   
45618  IRON BINDING CAPACITY, TOTAL (TIBC)      220.00            2   
45619                  IRON, TOTAL (SERUM)      108.33            2   
45620                             FERRITIN      211.25            2   
45621          HAEMOGLOBIN ELECTROPHORESIS      255.00            2   

       item_Sequence  item_RequestQuantity  item_ResponseQuantity  \
4                  1                   1.0                    1.0   
5                  1                   1.0                    0.0   
6                  2                   1.0                    0.0   
18                 1                   1.0                    1.0   
19                 2                   1.0                    1.0   
...              ...                   ...                    ...   
45617             11                   1.0                    1.0   
45618              1                   1.0                    1.0   
45619              2                   1.0                    1.0   
45620              3                   1.0                    1.0   
45621              4                   1.0                    1.0   

       transaction_DiagnosisIds  transaction_PhysicianIds item_ResponseState  
4                             7                      ,327           approved  
5                            17                      ,139           rejected  
6                            17                      ,139           rejected  
18                           14          ,238,238,238,238           approved  
19                           14          ,238,238,238,238           approved  
...                         ...                       ...                ...  
45617                        14  ,34,34,34,34,34,34,34,,,           approved  
45618                         1              296296296296           approved  
45619                 

In [4]:
X_train = df_train[train_columns[:-1]];  y_train = df_train[train_columns[-1]].values
X_test = df_test[train_columns[:-1]];  y_test = df_test[train_columns[-1]].values

y_train = encode_label(y_train); y_test = encode_label(y_test)

In [5]:
X= df_train[df_train.columns]
X

item_CreatedDate                 transaction_RequestId  \
4     2023-08-24 15:03:23.404  c4427a02-3291-422d-b2e8-b97bf3d5081d   
5     2023-08-29 11:48:54.060  e6f4ad37-13b9-4694-a61b-495384fcd245   
6     2023-08-29 11:48:54.060  e6f4ad37-13b9-4694-a61b-495384fcd245   
18    2023-08-29 12:35:53.514  bba44f35-42ea-4b22-aceb-8d8efaf45f9e   
19    2023-08-29 12:35:53.514  bba44f35-42ea-4b22-aceb-8d8efaf45f9e   
...                       ...                                   ...   
45617 2024-04-23 14:29:40.340  d62d5929-d94d-4a53-830d-168671bbea82   
45618 2024-04-23 16:20:30.584  da54b137-2aca-413a-9388-d9582ee72b57   
45619 2024-04-23 16:20:30.585  da54b137-2aca-413a-9388-d9582ee72b57   
45620 2024-04-23 16:20:30.585  da54b137-2aca-413a-9388-d9582ee72b57   
45621 2024-04-23 16:20:30.585  da54b137-2aca-413a-9388-d9582ee72b57   

       transaction_PatientAge  transaction_PatientEnGender  \
4                           6                            1   
5                          28                            0   
6                          28                            0   
18                         56                            0   
19                         56                            0   
...                       ...                          ...   
45617                      29                            1   
45618                       0                            1   
45619                       0                            1   
45620                       0                            1   
45621                       0                            1   

                               item_NameEn  item_Price  item_Status  \
4                              Examination       80.00            2   
5                              Examination       80.00            6   
6                   PREGNANCY TEST (BLOOD)      175.45            6   
18                             Examination       80.00            2   
19                               PERFALGAN      110.00            2   
...                                    ...         ...          ...   
45617            REPARIL  20 MG 40 DRAGEES       17.92            2   
45618  IRON BINDING CAPACITY, TOTAL (TIBC)      220.00            2   
45619                  IRON, TOTAL (SERUM)      108.33            2   
45620                             FERRITIN      211.25            2   
45621          HAEMOGLOBIN ELECTROPHORESIS      255.00            2   

       item_Sequence  item_RequestQuantity  item_ResponseQuantity  \
4                  1                   1.0                    1.0   
5                  1                   1.0                    0.0   
6                  2                   1.0                    0.0   
18                 1                   1.0                    1.0   
19                 2                   1.0                    1.0   
...              ...                   ...                    ...   
45617             11                   1.0                    1.0   
45618              1                   1.0                    1.0   
45619              2                   1.0                    1.0   
45620              3                   1.0                    1.0   
45621              4                   1.0                    1.0   

       transaction_DiagnosisIds  transaction_PhysicianIds item_ResponseState  
4                             7                      ,327           approved  
5                            17                      ,139           rejected  
6                            17                      ,139           rejected  
18                           14          ,238,238,238,238           approved  
19                           14          ,238,238,238,238           approved  
...                         ...                       ...                ...  
45617                        14  ,34,34,34,34,34,34,34,,,           approved  
45618                         1              296296296296           approved  
45619                 

In [7]:
lstm_embedding = LSTMEmbedding()
X_train_processed = lstm_embedding.preprocess_data(X_train)
X_train_processed

array([[  1,   0,   0, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0],
       [171,  81,   8, ...,   0,   0,   0],
       ...,
       [217, 107,  57, ...,   0,   0,   0],
       [268,   0,   0, ...,   0,   0,   0],
       [160, 577,   0, ...,   0,   0,   0]])

In [8]:
print('Training Model')
lstm_embedding.train_model(X_train_processed, y_train,epochs=3,batch_size=32)

print('Evaluating Model')
accuracy = lstm_embedding.evaluate_model(X_test, y_test)

print('Model Accuracy on test data: ',accuracy)

Training Model
Epoch 1/3
466/466 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - accuracy: 0.5394 - loss: 0.6801
Epoch 2/3
466/466 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.5874 - loss: 0.6271
Epoch 3/3
466/466 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5998 - loss: 0.6223
Evaluating Model
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5587 - loss: 0.6461
Model Accuracy on test data:  0.6211204528808594


In [9]:
lstm_embedding.input_shape

(16, 1)

In [10]:
X_test_vectorized = lstm_embedding.embedding_vector(X_test[:15],reload_model=False)
X_test_vectorized

array([[  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [549,  41, 140,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [ 66,   8,  58,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [136,  56,  57,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  7,   8,  18,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [ 85,  86,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [ 25,  30,  35,  28,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   

In [12]:
start_time = time.time()
lstm_encoder = LSTMEmbedding()
lstm_encoder.load_model()
X_test_vectorized = lstm_embedding.embedding_vector(X_test[:10],reload_model=True)

end_time = time.time()
execution_time = end_time - start_time
print("Execution time: {:.2f} seconds".format(execution_time))

Execution time: 0.54 seconds


In [13]:
X_test_vectorized

array([[286,  79, 269,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [120, 121,   5, 122, 123, 116,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [ 12,  13,  53,  23,  92,   4,  11,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  7,   8,  19,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  7,  46,  47,  48,   5,  10,   3,  38,  39,   3,   0,   0,   0,
          0,   0,   0],
       [ 73,  77,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [374,  76, 541, 494, 542, 430,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [151, 152,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0]])

In [16]:
def vectorize(COUNT_VALS):
      preds = lstm_encoder.embedding_vector(X_test[:COUNT_VALS],reload_model=True)


def calculate_excecution():
  exs = []
  COUNT_VALS = 50
  for i in range(10):
    start_time = time.time()

    vectorize(COUNT_VALS)

    end_time = time.time()

    execution_time = end_time - start_time
    exs.append(execution_time)

  average = np.array(exs).mean()
  return average/COUNT_VALS

calculate_excecution()

0.001722686767578125