In [11]:
from cashe import get_input
from src.data_local import MergedDataPreprocessing
from src.lstm_encoder import LSTMEmbedding
import time
from src.model_train import encode_label
import numpy as np

train_columns = ['item_NameEn','item_ResponseState']

In [27]:
df_original = get_input()
preprocessing = MergedDataPreprocessing(df_original)

df_original = preprocessing.age_gender_item_ids_prep(item_encoding=False)
df_train, df_test = preprocessing.train_test_split()

In [20]:
df_train

item_CreatedDate                 transaction_RequestId  \
27041          2024-01  203e1866-f81a-4a8e-a71c-6c932694b474   
15932          2023-11  ff79414b-e4b0-46a0-9a94-83e49d9f6720   
32890          2024-02  ca464cf3-89dc-4724-a7ef-e666b2f6d2af   
28215          2024-01  91ea6536-b509-447a-9b4a-04c95278d39c   
34409          2024-02  b6442563-2ca1-48c1-85d1-a80397623d5f   
...                ...                                   ...   
37307          2024-03  ff019cbe-aad7-4fa9-b8a1-d98dc1b9681a   
29951          2024-01  7e6c04dd-ae80-40ea-b066-785bdd91b721   
13259          2023-10  3ce711b1-e378-4ccb-b7a0-db71598bb4dd   
29375          2024-01  f59da168-8ad9-404d-a92f-cfcc05c537c1   
13575          2023-10  015480f2-fdbf-4b18-b75e-a0c7a3ba5b8d   

       transaction_PatientAge  transaction_PatientEnGender  \
27041                      44                            0   
15932                       8                            0   
32890                       5                            1   
28215                      56                            0   
34409                      10                            1   
...                       ...                          ...   
37307                      37                            0   
29951                      32                            0   
13259                      43                            0   
29375                      29                            0   
13575                      26                            1   

                                             item_NameEn  item_Price  \
27041                                        Examination   90.000000   
15932                      DEXAMETHASONE 8 MG/2 ML 5 AMP    8.550000   
32890                              STAINLESS STEEL CROWN  131.687308   
28215                   HAEMOGLOBIN A1C (GLYCOLATED HB )  216.670000   
34409  Intravenous administration of pharmacological ...   80.000000   
...                                                  ...         ...   
37307                                    PANORAMA X- RAY  100.000000   
29951                                    PARAFON 30  CAP   25.200000   
13259                                     DENGUE ANTIGEN  381.150000   
29375                                        Examination   80.000000   
13575                       I.V INJECTION    (INJ. ROOM)   41.000000   

       item_Status  item_Sequence  item_RequestQuantity  \
27041            2              1                   1.0   
15932            2              4                   1.0   
32890            6              8                   1.0   
28215            6              7                   1.0   
34409            6              6                   1.0   
...            ...            ...                   ...   
37307            6              2                   1.0   
29951            6             10                   1.0   
13259            2              9                   1.0   
29375            6              1                   1.0   
13575            2             10                   1.0   

       item_ResponseQuantity  transaction_DiagnosisIds  \
27041                    1.0                         4   
15932                    1.0                        14   
32890                    0.0                         8   
28215                    0.0                        11   
34409                    0.0                         7   
...                      ...                       ...   
37307                    0.0                         8   
29951                    0.0                        14   
13259                    1.0                        14   
29375                    0.0                        17   
13575                    1.0                        14   

                                transaction_PhysicianIds item_ResponseState  
27041                                              ,,288           approved  
15932                                   ,327,327,327,327         

In [12]:
X_train = df_train[train_columns[:-1]];  y_train = df_train[train_columns[-1]].values
X_test = df_test[train_columns[:-1]];  y_test = df_test[train_columns[-1]].values

y_train = encode_label(y_train); y_test = encode_label(y_test)

In [25]:
X= df_train[df_train.columns]
X

item_CreatedDate                 transaction_RequestId  \
27041          2024-01  203e1866-f81a-4a8e-a71c-6c932694b474   
15932          2023-11  ff79414b-e4b0-46a0-9a94-83e49d9f6720   
32890          2024-02  ca464cf3-89dc-4724-a7ef-e666b2f6d2af   
28215          2024-01  91ea6536-b509-447a-9b4a-04c95278d39c   
34409          2024-02  b6442563-2ca1-48c1-85d1-a80397623d5f   
...                ...                                   ...   
37307          2024-03  ff019cbe-aad7-4fa9-b8a1-d98dc1b9681a   
29951          2024-01  7e6c04dd-ae80-40ea-b066-785bdd91b721   
13259          2023-10  3ce711b1-e378-4ccb-b7a0-db71598bb4dd   
29375          2024-01  f59da168-8ad9-404d-a92f-cfcc05c537c1   
13575          2023-10  015480f2-fdbf-4b18-b75e-a0c7a3ba5b8d   

       transaction_PatientAge  transaction_PatientEnGender  \
27041                      44                            0   
15932                       8                            0   
32890                       5                            1   
28215                      56                            0   
34409                      10                            1   
...                       ...                          ...   
37307                      37                            0   
29951                      32                            0   
13259                      43                            0   
29375                      29                            0   
13575                      26                            1   

                                             item_NameEn  item_Price  \
27041                                        Examination   90.000000   
15932                      DEXAMETHASONE 8 MG/2 ML 5 AMP    8.550000   
32890                              STAINLESS STEEL CROWN  131.687308   
28215                   HAEMOGLOBIN A1C (GLYCOLATED HB )  216.670000   
34409  Intravenous administration of pharmacological ...   80.000000   
...                                                  ...         ...   
37307                                    PANORAMA X- RAY  100.000000   
29951                                    PARAFON 30  CAP   25.200000   
13259                                     DENGUE ANTIGEN  381.150000   
29375                                        Examination   80.000000   
13575                       I.V INJECTION    (INJ. ROOM)   41.000000   

       item_Status  item_Sequence  item_RequestQuantity  \
27041            2              1                   1.0   
15932            2              4                   1.0   
32890            6              8                   1.0   
28215            6              7                   1.0   
34409            6              6                   1.0   
...            ...            ...                   ...   
37307            6              2                   1.0   
29951            6             10                   1.0   
13259            2              9                   1.0   
29375            6              1                   1.0   
13575            2             10                   1.0   

       item_ResponseQuantity  transaction_DiagnosisIds  \
27041                    1.0                         4   
15932                    1.0                        14   
32890                    0.0                         8   
28215                    0.0                        11   
34409                    0.0                         7   
...                      ...                       ...   
37307                    0.0                         8   
29951                    0.0                        14   
13259                    1.0                        14   
29375                    0.0                        17   
13575                    1.0                        14   

                                transaction_PhysicianIds item_ResponseState  
27041                                              ,,288           approved  
15932                                   ,327,327,327,327         

In [13]:
lstm_embedding = LSTMEmbedding()
X_train_processed = lstm_embedding.preprocess_data(X_train)
X_train_processed

array([[  1,   0,   0, ...,   0,   0,   0],
       [ 62,  52,   6, ...,   0,   0,   0],
       [257, 258, 167, ...,   0,   0,   0],
       ...,
       [134, 108,   0, ...,   0,   0,   0],
       [  1,   0,   0, ...,   0,   0,   0],
       [ 16,  44,  21, ...,   0,   0,   0]])

In [10]:
print('Training Model')
lstm_embedding.train_model(X_train_processed, y_train,epochs=3,batch_size=32)

print('Evaluating Model')
accuracy = lstm_embedding.evaluate_model(X_test, y_test)

print('Model Accuracy on test data: ',accuracy)

Training Model
Epoch 1/3
468/468 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.5297 - loss: 0.6871
Epoch 2/3
468/468 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.6246 - loss: 0.6333
Epoch 3/3
468/468 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.6407 - loss: 0.6028
Evaluating Model
118/118 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6438 - loss: 0.5868
Model Accuracy on test data:  0.5913405418395996


In [8]:
lstm_embedding.input_shape

(16, 1)

In [10]:
X_test_vectorized = lstm_embedding.embedding_vector(X_test[:15],reload_model=False)
X_test_vectorized

array([[302,  78, 266,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [120, 121,   5, 122, 123, 114,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [ 12,  13,  54,  22,  93,   4,  11,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  7,   8,  19,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  7,  48,  49,  50,   5,  10,   3,  39,  40,   3,   0,   0,   0,
          0,   0,   0],
       [ 73,  77,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [348,  75, 531, 446, 532, 447,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [149, 150,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [ 33,  43,  24,  44,  2

In [12]:
start_time = time.time()
lstm_encoder = LSTMEmbedding()
lstm_encoder.load_model()
X_test_vectorized = lstm_embedding.embedding_vector(X_test[:10],reload_model=True)

end_time = time.time()
execution_time = end_time - start_time
print("Execution time: {:.2f} seconds".format(execution_time))

Execution time: 0.54 seconds


In [13]:
X_test_vectorized

array([[286,  79, 269,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [120, 121,   5, 122, 123, 116,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [ 12,  13,  53,  23,  92,   4,  11,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  7,   8,  19,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [  7,  46,  47,  48,   5,  10,   3,  38,  39,   3,   0,   0,   0,
          0,   0,   0],
       [ 73,  77,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [374,  76, 541, 494, 542, 430,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0],
       [151, 152,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0]])

In [16]:
def vectorize(COUNT_VALS):
      preds = lstm_encoder.embedding_vector(X_test[:COUNT_VALS],reload_model=True)


def calculate_excecution():
  exs = []
  COUNT_VALS = 50
  for i in range(10):
    start_time = time.time()

    vectorize(COUNT_VALS)

    end_time = time.time()

    execution_time = end_time - start_time
    exs.append(execution_time)

  average = np.array(exs).mean()
  return average/COUNT_VALS

calculate_excecution()

0.001722686767578125